#: import AboutScreen libs.features.about.about_screen.AboutScreen
#: import SettingsScreen libs.features.settings.settings_screen.SettingsScreen

#: include libs/theme/theme.kv

MDScreen:
    id: main_screen
    appName: "Open Mindset"
    MDTopAppBar:
        title: root.appName
        md_bg_color: app.theme_cls.primary_color
        pos_hint: {"top": 1}
        left_action_items:
            [['menu', lambda _: nav_drawer.set_state("open")]]
        right_action_items:
            [['information-outline', lambda _: app.show_info()]]

    MDNavigationLayout:
        MDScreenManager:
            id: screen_manager
            MDScreen:
                name: "home"
                AppScreenLayout:
                    MDList:
                        id: chat_list
                        padding: 0, 0, 0, 0
                    BoxLayout:
                        MDTextField:
                            id: chat_input_text
                            hint_text: "Query message"
                            helper_text: "Type your query message here"
                            helper_text_mode: "on_focus"
                            max_text_length: 1024
                            multiline: True
                        MDIconButton:
                            icon: "send"
                            on_release: app.send_message(chat_input_text.text)
            MDScreen:
                name: "settings"
                SettingsScreen:
            MDScreen:
                name: "about"
                AboutScreen:
        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)
            theme_text_color: "Primary"
            MDNavigationDrawerMenu:
                MDNavigationDrawerHeader:
                    source: "logo.png"
                    title: root.appName
                    text: " Native app powered by Python"
                    text_font_style: "Body2"
                    spacing: "4dp"
                    padding: 0, 0, 0, "32dp"
                MDNavigationDrawerItem:
                    icon: "home"
                    text: "Home screen"
                    theme_text_color: "Primary"
                    on_release:
                        screen_manager.current = "home"
                        nav_drawer.set_state("close")
                MDNavigationDrawerItem:
                    icon: "cog"
                    text: "Settings"
                    theme_text_color: "Primary"
                    on_release:
                        screen_manager.current = "settings"
                        nav_drawer.set_state("close")
                MDNavigationDrawerItem:
                    icon: "information"
                    text: "About this app..."
                    theme_text_color: "Primary"
                    on_release:
                        screen_manager.current = "about"
                        nav_drawer.set_state("close")
                MDNavigationDrawerDivider:
                MDNavigationDrawerItem:
                    icon: "exit-to-app"
                    text: "Exit"
                    theme_text_color: "Primary"
                    on_release:
                        nav_drawer.set_state("close")
                        app.exit()
