#: include libs/theme/theme.kv

#: import HomeScreen libs.features.home.home_screen.HomeScreen
#: import AboutScreen libs.features.about.about_screen.AboutScreen
#: import SettingsScreen libs.features.settings.settings_screen.SettingsScreen
#: import AppNavigationBar libs.theme.app_navigation_bar.AppNavigationBar

<AppScreen>:
    AppNavigationBar:
        id: app_navigation_bar
        title: app.get_metadata()["name"]
        md_bg_color: app.theme_cls.primary_color
        pos_hint: {"top": 1}
        nav_drawer: nav_drawer

    MDNavigationLayout:
        MDScreenManager:
            id: screen_manager
            HomeScreen:
                name: "home"
            SettingsScreen:
                name: "settings"
            AboutScreen:
                name: "about"
        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)
            theme_text_color: "Primary"
            MDNavigationDrawerMenu:
                MDNavigationDrawerHeader:
                    source: "libs/assets/logo.png"
                    size_hint: 1, None
                    title: app.get_metadata()["name"]
                    text: app.get_metadata()["description"]
                    text_font_style: "Body2"
                    spacing: "4dp"
                    padding: 0, 0, 0, "32dp"
                MDNavigationDrawerItem:
                    icon: "home"
                    text: "Home screen"
                    theme_text_color: "Primary"
                    on_release: app_navigation_bar.navigate_to("home")
                MDNavigationDrawerItem:
                    icon: "cog"
                    text: "Settings"
                    theme_text_color: "Primary"
                    on_release: app_navigation_bar.navigate_to("settings")
                MDNavigationDrawerItem:
                    icon: "information"
                    text: "About this app..."
                    theme_text_color: "Primary"
                    on_release: app_navigation_bar.navigate_to("about")
                MDNavigationDrawerDivider:
                MDNavigationDrawerItem:
                    icon: "exit-to-app"
                    text: "Exit"
                    theme_text_color: "Primary"
                    on_release:
                        app_navigation_bar.close_menu()
                        app.exit()
