<Text2ImgScreen>
    AppScreenLayout:
        ScrollView:
            id: scroll_view
            do_scroll_x: False
            do_scroll_y: True
            always_overscroll: False
            MDBoxLayout:
                orientation: "vertical"
                id: scroll_view_box
                adaptive_height: True
                spacing: dp(4)
                MDRectangleFlatIconButton:
                    id: more_info_button
                    icon: "image"
                    text: "Text to Image"
                    on_release: print("Text2ImgScreen")
                    pos_hint: {"center_x": 0.5}
