<AppScreenLayout@MDBoxLayout>:
    orientation: "vertical"
    padding: "16dp", "80dp", "16dp", "16dp"

<AdaptativeVerticalCardLayout@MDBoxLayout>
    adaptive_height: True
    orientation: "vertical"
    padding: dp(8)
    canvas.before:
        Color:
            rgba: app.theme_cls.primary_color
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: 0, -10
            spread_radius: -20, -20
            border_radius: dp(10), dp(10), dp(10), dp(10)
            blur_radius: 20
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [dp(10),]

<AdaptativeLabelBox@MDBoxLayout>:
    orientation: "vertical"
    adaptive_height: True
    MDLabel:
        id: label
        adaptive_height: True
        text: ""
        color: app.theme_cls.text_color
        font_style: "Body2"
