<HomeScreen>
    AppScreenLayout:
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            MDBoxLayout:
                orientation: "vertical"
                id: chat_list
                adaptive_height: True
                spacing: dp(4)
        MDBoxLayout:
            adaptive_height: True
            MDTextField:
                id: chat_input_text
                hint_text: "Query message"
                helper_text: "Type your query message here"
                helper_text_mode: "on_focus"
                max_text_length: 1024
                multiline: True
            MDIconButton:
                icon: "send"
                on_release: root.send_message(chat_input_text.text)
