<AboutScreen>
    AppScreenLayout:
        BoxLayout:
            orientation: "vertical"
            MDRectangleFlatIconButton:
                id: more_info_button
                icon: "information"
                text: "About this app..."
                on_release: root.more_info()
                size_hint: None, None
                pos_hint: {"center_x": 0.5}
            BoxLayout:
                size_hint: 1, 1
