#:import hex kivy.utils.get_color_from_hex
#:import AppDataTable libs.theme.app_data_table.AppDataTable

<AboutScreen>
    AppScreenLayout:
        MDBoxLayout:
            orientation: "vertical"
            spacing: dp(10)

            AdaptativeVerticalCardLayout:
                MDBoxLayout:
                    adaptive_height: True
                    orientation: "horizontal"
                    padding: dp(10)
                    spacing: dp(10)
                    Image:
                        source: "libs/assets/logo.png"
                        size_hint: None, None
                        size: 160, 160
                        pos_hint: {"center_x": 0.5, "top": 1}
                        fit_mode: "contain"
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        MDLabel:
                            adaptive_height: True
                            text: "Free application originally created to learn the Python language in our spare time.\n\nThe goals for developers is to learn a technology at the same time as providing a fun and scalable utility app. The source code of this application is available and can be used as a learning base for training sessions in Python programming with KivyMD!"
                            font_style: "Body2"
            AppDataTable:
                id: infos_panel
                size_hint: 1, 1
                use_pagination: True
                column_data: [("System key", dp(40)), ("Detail", dp(root.width))]
                row_data: []
            MDRectangleFlatIconButton:
                id: more_info_button
                adaptive_height: True
                icon: "information"
                text: "About this app..."
                on_release: root.more_info()
                size_hint: None, None
                pos_hint: {"center_x": 0.5}
