#:import hex kivy.utils.get_color_from_hex

<AboutScreen>
    AppScreenLayout:
        BoxLayout:
            orientation: "vertical"
            spacing: dp(10)

            MDBoxLayout:
                adaptive_height: True
                orientation: "vertical"
                padding: dp(8)
                canvas.before:
                    Color:
                        rgba: hex('#696969')
                    BoxShadow:
                        pos: self.pos
                        size: self.size
                        offset: 0, -10
                        spread_radius: -20, -20
                        border_radius: dp(10), dp(10), dp(10), dp(10)
                        blur_radius: 40
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [dp(10),]

                MDBoxLayout:
                    adaptive_height: True
                    orientation: "horizontal"
                    padding: dp(10)
                    spacing: dp(10)
                    Image:
                        source: "libs/assets/logo.png"
                        size_hint: None, None
                        size: 160, 160
                        pos_hint: {"center_x": 0.5, "top": 1}
                        fit_mode: "contain"
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        MDLabel:
                            id: app_description
                            adaptive_height: True
                            text: "Free application originally created to learn the Python language in our spare time.\n\nThe goals for developers is to learn a technology at the same time as providing a fun and scalable utility app. The source code of this application is available and can be used as a learning base for training sessions in Python programming with KivyMD!"
                            font_style: "Body2"

            MDRectangleFlatIconButton:
                id: more_info_button
                icon: "information"
                text: "About this app..."
                on_release: root.more_info()
                size_hint: None, None
                pos_hint: {"center_x": 0.5}
            BoxLayout:
                size_hint: 1, 1
