#:import Window kivy.core.window.Window
#:import m_res kivymd.material_resources

<MDNavigationDrawerHeaderOM>
    adaptive_height: True

    # costa-rica: replaced FitImage with BoxLayout with image. FitImage seems to get too big with iOS. Problem can be reproduced when running on python when window width is shrunk
    # FitImage:
    #     id: logo
    #     source: root.source
    #     size_hint: None, None
    #     size: label_box.height, label_box.height
    BoxLayout:
        orientation: "vertical"
        Label:
            text:""
        Image:
            size_hint_y:None
            height:self.width
            source: root.source
            allow_stretch: True
            keep_ratio: False
        Label:
            text:""
    MDBoxLayout:
        id: label_box
        orientation: "vertical"
        adaptive_height: True

        MDLabel:
            id: title
            adaptive_height: True
            halign: root.title_halign
            text: root.title
            font_style: root.title_font_style
            font_size: root.title_font_size
            color:
                root.title_color \
                if root.title_color else \
                app.theme_cls.text_color

        MDLabel:
            id: text
            adaptive_height: True
            text: root.text
            halign: root.text_halign
            font_style: root.text_font_style
            font_size: root.text_font_size
            color:
                root.text_color \
                if root.text_color else \
                app.theme_cls.text_color
