<SettingsScreen>
    AppScreenLayout:
        MDRectangleFlatIconButton:
            icon: "theme-light-dark"
            text: "Set dark theme" if app.theme_cls.theme_style == "Light" else "Set light theme"
            on_release: root.toggle_theme()

        MDSwitch:
            size_hint: None, None
            size: "48dp", "48dp"
            active: True if app.theme_cls.theme_style == "Dark" else False
